lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'Rogue One' # required for token creation, usage of an environment variable is recommended
    user_identity_field: 'username'
#    token_ttl:        3600
