security:
    encoders:
        App\Entity\ResearchUser:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\ResearchUser
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public_auth:
            pattern: ^/api/auth/(register|check-email|login)
            stateless: true
            anonymous: true


        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }