#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#register:
#    path: /register
#    controller: App\Controller\AuthController::register
#    methods: POST
#
api:
    path: /api
    controller: App\Controller\AuthController::api
#goodreads:
#    path: /goodreads
#    controller: App\Controller\GoodreadsController::index

#login_check:
#    path:     /login_check
#    methods:  [POST]